# this file is automatically generated
import pickle as pk
import os
from tools.parsetxt import __try_load_cpp
from project_root import *

__dir, _ = os.path.split(__file__)


def __try_load(var: str):
    try:
        with open(pjoin(__dir, f"{var}.pickle"), "rb") as f:
            return pk.load(f)
    except Exception:
        return None


